name: PHP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd php
          composer install --prefer-dist --no-progress

      - name: Run tests
        run: |
          cd php
          composer run-script tests
